### ISSUE TITLE
downloading data

### ISSUE THREAD

**Issue by mikelee-dev** [fferflo/statewide-visual-geolocalization#3]
this error occurs frequently when running: ```./download_nconemap.py``` :

```docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Output worker got exception:
Traceback (most recent call last):
  File "/home/ubuntu/geoestimation/miniconda3/envs/statewide/lib/python3.12/site-packages/tinypl/process.py", line 470, in work
    value = func(value)
            ^^^^^^^^^^^
  File "/home/ubuntu/geoestimation/statewide-visual-geolocalization/download_scripts/./download_nconemap.py", line 221, in process
    run_docker(f"gdal_translate --config GDAL_CACHEMAX 512 -co COMPRESS=JPEG -co TILED=YES -co NUM_THREADS=1 -co BIGTIFF=YES -b 1 -b 2 -b 3 {name}.sid {name}.tif")
  File "/home/ubuntu/geoestimation/statewide-visual-geolocalization/download_scripts/./download_nconemap.py", line 180, in run_docker
    raise Exception(f"Error running command: {cmd}")
Exception: Error running command: gdal_translate --config GDAL_CACHEMAX 512 -co COMPRESS=JPEG -co TILED=YES -co NUM_THREADS=1 -co BIGTIFF=YES -b 1 -b 2 -b 3 Anson_2023.sid Anson_2023.tif```


the docker commands work for some of the other counties in north carolina.

**Comment by fferflo** [comment]
You could try running the failed command

```bash
gdal_translate --config GDAL_CACHEMAX 512 -co COMPRESS=JPEG -co TILED=YES -co NUM_THREADS=1 -co BIGTIFF=YES -b 1 -b 2 -b 3 Anson_2023.sid Anson_2023.tif
```

directly from command line (by logging into [the docker image](https://hub.docker.com/r/klokantech/gdal/) first) and check whether it fails there as well, and what the error message is. Alternatively, running `./download_nconemap.py` with `--workers 1` will also print all error messages, but take longer.

I unfortunately did not find an easy way to convert the *.sid files that are downloaded from the map provider other than by running gdal through this docker image.

**Comment by parhamkebria** [comment]
Hello.
Running download_nconemap.py gets stuck at "Downloading areas: 0%" even after an hour! The other download scripts run with no issue. Is there any specific fix or alternative for "nconemap"? I already have gdal installed.
Thanks in advance!
